bifefootball/urls.py
from django.contrib import admin
from django.urls import path, include

from players.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path("matches/", include("matches.urls", namespace="matches")),
    path("admins/", include("admins.urls", namespace="admins")),
    path("players/", include("players.urls", namespace="players")),
    path("organizations/", include("organizations.urls", namespace="organizations")),
    path("teams/", include("teams.urls", namespace="teams")),
    path('accounts/', include('allauth.urls')),
    path("custommatches/", include("custommatches.urls", namespace="custommatches")),
]

custommatches/urls.py
from django.urls import path

from .views import CustomMatchCreateView, CustomMatchCreateEventView, CustomMatchDetailView, CustomResultCreateView, CustomMatchPlayerStatCreateEventView

"""
BASE ENDPOINT /custommatches
"""
app_name = "custommatches"

urlpatterns = [
    path("create/", CustomMatchCreateView.as_view(), name='custommatch-create'),
    path("custom-result/<slug:slug>", CustomResultCreateView.as_view(), name='custom-create-result'),
    path("custom-playerstat/<slug:slug>/", CustomMatchPlayerStatCreateEventView.as_view(), name='custom-playerstat-create'),
    path("custom-event/<slug:slug>/", CustomMatchCreateEventView.as_view(), name='custommatch-event-create'),
    path("<slug:slug>/", CustomMatchDetailView.as_view(), name='custommatch-detail'),
]

matches/urls.py
from django.urls import path
from .views import (
    MatchListView,
    MatchDetailView,
    MatchCreateView,
    MatchCreateEventView,
    ResultCreateView,
    PlayerStatCreateEventView,
    UpdateTeamsView,
    )

"""
BASE ENDPOINT /matches
"""
app_name = "matches"

urlpatterns = [
    path("", MatchListView.as_view(), name='match-list'),
    path("create/", MatchCreateView.as_view(), name='match-create'),
    path("create-event/<slug:slug>/", MatchCreateEventView.as_view(), name='match-event-create'),
    path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path('update-teams/', UpdateTeamsView.as_view(), name='update-teams'),
    path("create-playerstat/<slug:slug>/", PlayerStatCreateEventView.as_view(), name='player-stat-create'),
    path("<slug:slug>/", MatchDetailView.as_view(), name='match-detail'),
]

players/urls.py
from django.urls import path
from .views import (
    PlayerListView,
    PlayerDetailView,
    PlayerCreateView,
    PlayerUpdateView,
    PlayerDeleteView,
    PlayerMatchesListView,
    PlayerUpdateTeamsView,
    TeamSelectView,
    )

"""
BASE ENDPOINT /players
"""
app_name = "players"

urlpatterns = [
    path("", PlayerListView.as_view(), name='player-list'),
    path("create/", PlayerCreateView.as_view(), name='player-create'),
    path('select-team/', TeamSelectView.as_view(), name='team-select'),
    path("<slug:slug>/", PlayerDetailView.as_view(), name='player-detail'),
    path("<slug:slug>/update", PlayerUpdateView.as_view(), name='player-update'),
    path('<slug:slug>/update-teams/', PlayerUpdateTeamsView.as_view(), name='player-update-teams'),
    path("<slug:slug>/delete", PlayerDeleteView.as_view(), name='player-delete'),
    path("<slug:slug>/matches", PlayerMatchesListView.as_view(), name='player-matches'),
]

teams/urls.py
from django.urls import path
from .views import (
    TeamListView,
    TeamCreateView,
    TeamDetailView,
    TeamDashboardView,
    TeamMatchesView,
    CoachCreateView,
    TeamSelectView
    )

"""
BASE ENDPOINT /teams
"""
app_name = "teams"

urlpatterns = [
    path("", TeamListView.as_view(), name='team-list'),
    path("create/", TeamCreateView.as_view(), name='team-create'),
    path("create-coach/", CoachCreateView.as_view(), name='coach-create'),
    path('select-team/', TeamSelectView.as_view(), name='team-select'),
    path("team-dashboard/", TeamDashboardView.as_view(), name='team-dashboard'),
    # path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path("<slug:slug>/team-matches", TeamMatchesView.as_view(), name='team-matches'),
    path("<slug:slug>/", TeamDetailView.as_view(), name='team-detail'),
]

players/forms.py
from django import forms
from .models import Player, Team, User


class PlayerModelForm(forms.ModelForm):
    # username = forms.CharField(max_length=20, required=True, label="Player's Username")
    # email = forms.CharField(max_length=45, required=True, label="Email")

    class Meta:
        model = Player
        fields = ("first_name", "last_name", "shirt_number", "age", "position")
    # teams = forms.ModelChoiceField(queryset=Team.objects.all())

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(PlayerModelForm, self).__init__(*args, **kwargs)
        

class PlayerModelUpdateForm(forms.ModelForm):
    class Meta:
        model = Player
        fields =("first_name", "last_name", "shirt_number", "age", "position")


class PlayerTeamForm(forms.ModelForm):
    teams = forms.ModelMultipleChoiceField(queryset=Team.objects.all(), widget=forms.CheckboxSelectMultiple, required=False)
    
    class Meta:
        model = Player
        fields = ['teams']

    def __init__(self, *args, **kwargs):
        super(PlayerTeamForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['teams'].initial = self.instance.teams.all()

players/views.py
import random
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views import generic
from django.core.exceptions import PermissionDenied
from django.contrib import messages
from faker import Faker
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Sum, Count, Q

from .mixins import CoachRequiredMixin, AdminRequiredMixin
from .models import Player, PlayerStat, Contract, MatchEvent, Coach, Team, User
from .forms import PlayerModelForm, PlayerModelUpdateForm, PlayerTeamForm
from custommatches.models import CustomMatchPlayerStat, CustomMatchEvent


class LandingPageView(generic.TemplateView):
    template_name = "landing_page.html"


class PlayerListView(generic.ListView):
    template_name = "players/player_list.html"
    context_object_name = "players"

    def get_queryset(self):
        return Player.objects.all().order_by('id')
    
    def get(self, request, *args, **kwargs):
        search = request.GET.get('search')
        qs = self.get_queryset()
        if search:
            qs = self.get_queryset().filter(Q(first_name__icontains=search) | Q(last_name__icontains=search))

        paginator = Paginator(qs, 15)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        if request.htmx:
            return render(request, 'players/partials/partial_player_list.html', {'page_obj': page_obj})
        else:
            return render(request, 'players/player_list.html', {'page_obj': page_obj})


class PlayerMatchesListView(generic.DetailView):
    template_name = "players/players_matches.html"
    context_object_name = "player"

    def get_queryset(self):
        queryset = Player.objects.all()

        return queryset
    
    def get_context_data(self, **kwargs):
        player = Player.objects.get(slug=self.kwargs['slug'])
        context = super(PlayerMatchesListView, self).get_context_data(**kwargs)
        queryset = PlayerStat.objects.filter(player=self.get_object())
        custom_qs = CustomMatchPlayerStat.objects.filter(player=player)
        context.update({
            "stats": queryset,
            "custom_qs": custom_qs
        })

        return context
    

class PlayerDetailView(generic.DetailView):
    template_name = "players/player_detail.html"
    context_object_name = "player"

    def get_queryset(self):
        return Player.objects.all()
    
    def get_context_data(self, **kwargs):
        request_user = self.request.user
        player = Player.objects.get(slug=self.kwargs['slug'])
        context = super(PlayerDetailView, self).get_context_data(**kwargs)
        contract = Contract.objects.filter(is_valid=True, player=self.get_object()).order_by('-contract_date').first()
        latest_events = MatchEvent.objects.filter(player_contract=contract).order_by('-timestamp')[:5]
        custom_events = CustomMatchEvent.objects.filter(player_contract=contract).order_by('-timestamp')[:5]
        queryset = PlayerStat.objects.filter(player=self.get_object())
        custom_qs = CustomMatchPlayerStat.objects.filter(player=player)

        custom_stats = custom_qs.aggregate(
                goals = Sum('goals', default=0),
                assists = Sum('assists', default=0),
                minutes_played = Sum('minutes_played', default=0),
                games = Count("custom_match")),
        
        context.update({
            "stats": queryset.aggregate(
                goals = Sum('goals', default=0) + custom_stats[0]["goals"],
                assists = Sum('assists', default=0) + custom_stats[0]["assists"],
                minutes_played = Sum('minutes_played', default=0) + custom_stats[0]["minutes_played"],
                games = Count("match") + custom_stats[0]["games"]
                ),
            "contract": contract,
            "latest_events": latest_events,
            "custom_events": custom_events
        })

        if hasattr(request_user, 'coach'):
            coach_team = Team.objects.get(coach__user=request_user)
            if contract.team  ==  coach_team:
                player_obj = Player.objects.get(id=contract.player.id, teams=coach_team)
                if not player_obj.teams.filter(coach__user=self.request.user).exists():
                    messages.error(self.request, "Player is not part of your team")
                context["is_coach_player"] = True
            else:
                context["is_coach_player"] = False
        else:
            messages.error(self.request, "View details only")
            context["is_coach_player"] = False
        
        return context
    

class PlayerCreateView(LoginRequiredMixin, CoachRequiredMixin, generic.CreateView):
    template_name = "players/player_create.html"
    form_class = PlayerModelForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(PlayerCreateView, self).get_form_kwargs(**kwargs)
        kwargs.update({'user': self.request.user})
        return kwargs

    def get_context_data(self, **kwargs):
        context = super(PlayerCreateView, self).get_context_data(**kwargs)
        coach = get_object_or_404(Coach, user=self.request.user)
        context = {'coach_teams': Team.objects.filter(coach=coach),
        'coach_team_id': self.get_selected_team_id(),
        'form': PlayerModelForm(user=self.request.user)
        }

        return context

    def get_selected_team_id(self):
        selected_team_id = self.request.session.get('coach_team_id')
        request_user = self.request.user

        if selected_team_id is None:
            if hasattr(request_user, 'coach'):
                coach = get_object_or_404(Coach, user=request_user)
                teams = Team.objects.filter(coach=coach)
                if teams.exists():
                    selected_team_id = teams.first().id
                    self.request.session['coach_team_id'] = selected_team_id
            else:
                messages.error(self.request, "Action not permitted! Must be a coach")
                return render(self.request, 'landing_page')

        return selected_team_id
    
    def get_success_url(self):
        return reverse("players:player-list")
    
    def form_valid(self, form):
        # fake = Faker()
        # random_password = f"{random.randint(0, 100000)}"
        # user = User.objects.create_user(
        #     username=form.cleaned_data.get('username'), 
        #     first_name=form.cleaned_data.get('first_name'),
        #     last_name=form.cleaned_data.get('last_name'),
        #     password=random_password
        # )
        # user.is_player = True
        # user.save()

        # Create the Player object
        player = form.save(commit=False)
        # player.user = user
        player.save()

        # Get the selected team ID from the session or form
        selected_team_id = self.get_selected_team_id()
        if selected_team_id:
            selected_team = get_object_or_404(Team, id=selected_team_id)
            player.teams.add(selected_team)
        return super(PlayerCreateView, self).form_valid(form)


class TeamSelectView(LoginRequiredMixin, CoachRequiredMixin, generic.View):
    def post(self, request, *args, **kwargs):
        selected_team_id = request.POST.get('team')
        request.session['coach_team_id'] = selected_team_id
        return redirect('players:player-create')
    

class PlayerUpdateView(LoginRequiredMixin, CoachRequiredMixin, generic.UpdateView):
    template_name = "players/player_update.html"
    form_class = PlayerModelUpdateForm
    context_object_name = "player"

    def get_queryset(self):
        player = Player.objects.filter(slug=self.kwargs.get('slug'))
        return player
        
    def get_object(self, queryset=None):
        """
        Override get_object to ensure the coach is part of the player's team.
        """
        obj = Player.objects.get(slug=self.kwargs.get('slug'))
        if not obj.teams.filter(coach__user=self.request.user).exists():
            raise PermissionDenied("You do not have permission to update this player.")
        return obj
        
    def get_success_url(self):
        return reverse("players:player-detail", kwargs={'slug': self.object.slug})
    

class PlayerDeleteView(LoginRequiredMixin, CoachRequiredMixin, generic.DeleteView):
    template_name = "players/player_delete.html"
    context_object_name = "player"
    
    def get_queryset(self):
        user = self.request.user
        # initial queryset of players for entire team  
        return Player.objects.all()     
        # return Player.objects.filter(teams=user)

    def get_success_url(self):
        return reverse("players:player-list")
    

class PlayerUpdateTeamsView(LoginRequiredMixin, CoachRequiredMixin, generic.UpdateView):
    model = Player
    form_class = PlayerTeamForm
    template_name = 'players/player_update_teams.html'
    
    def form_valid(self, form):
        player = form.save(commit=False)
        player.teams.set(form.cleaned_data['teams'])
        player.save()
        return redirect('players:player-detail', slug=player.slug)

    def get_success_url(self):
        return reverse('players:player-detail', kwargs={'slug': self.object.slug})

players/templates/players/player_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
  <div class="flex justify-center mt-10">
    <a class="text-blue-800" href="{% url 'players:player-list'%}">Back to player list</a>
  </div>

  <div class="flex justify-center py-5 border-gray-200">
    <h1 class="text-4xl text-gray-800">Create a new player</h1>
  </div>

  <div class="max-w-lg mx-auto mb-3">
    <form id="team-select-form" method="post" action="{% url 'players:team-select' %}" class="mt-5">
      {% csrf_token %}
      <label for="team" class="block text-sm font-medium text-black">Select Team:</label>
      <div class="mt-1">
        <select id="team" class="form-select block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 rounded-md" name="team" onchange="document.getElementById('team-select-form').submit();">
          {% for team in coach_teams %}
            <option value="{{ team.id }}" {% if team.id == coach_team_id or forloop.first %}selected{% endif %}>{{ team.team_name }}</option>
          {% endfor %}
        </select>
      </div>
    </form>
  </div>

  <form method="post"class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md mb-10">Submit</button>
    </form>
  </form>

</div>

{% endblock content %}

players/templates/players/player_delete.html
{% extends "base.html" %} 
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
  <div class="flex justify-center mt-10">
    <a class="text-blue-800 hover:text-blue-500 mt-3" href="{% url 'players:player-list'%}"> Go back to plyers list</a>
  </div>

  <div class="flex justify-center py-5 border-gray-200">
    <h1 class="text-4xl text-gray-800">Delete this player?</h1>
  </div>

  <form method="post"class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
  </form>

</div>

{% endblock content %}

players/templates/players/player_detail.html
{% extends "base.html" %}

{% block content %}

<div class="bg-white relative shadow rounded-lg w-5/6 md:w-5/6 lg:w-4/6 xl:w-3/6 mx-auto mt-14">
  <div class="flex justify-center relative">
    {% comment %} <img src="https://avatars0.githubusercontent.com/u/35900628?v=4" alt="" class="rounded-full mx-auto absolute -top-16 w-32 h-32 shadow-md border-4 border-white transition duration-200 transform hover:scale-110"> {% endcomment %}
  </div>
    
  <div class="mt-14">
    <h1 class="font-bold text-center text-3xl text-gray-900">{{ player }}</h1>
    <p class="text-center text-sm text-gray-400 font-medium mb-4">
      <span class="mr-6">Position: {{ player.position }}</span> | Age: {{ player.age }}
    </p>
    <div class="my-5 px-6">
      <a href="#" class="text-gray-200 block rounded-lg text-center font-medium leading-6 px-6 py-3 bg-gray-900 hover:bg-black hover:text-white">Plays for <span class="font-bold">{{ contract.team }}</span></a>
    </div>
    <div class="flex justify-between items-center my-5 px-6">
        <a href="#" class="text-gray-500 hover:text-gray-900 hover:bg-gray-100 rounded transition duration-150 ease-in font-medium text-sm text-center w-full py-3">{{ stats.goals }} Goal(s)</a>
        <a href="#" class="text-gray-500 hover:text-gray-900 hover:bg-gray-100 rounded transition duration-150 ease-in font-medium text-sm text-center w-full py-3">{{ stats.assists }} Assist(s)</a>
        <a href="{% url 'players:player-matches' player.slug%}" class="text-gray-500 hover:text-gray-900 hover:bg-gray-100 rounded transition duration-150 ease-in font-medium text-sm text-center w-full py-3">{{ stats.games }} Game(s)</a>
        <a href="" class="text-gray-500 hover:text-gray-900 hover:bg-gray-100 rounded transition duration-150 ease-in font-medium text-sm text-center w-full py-3">{{ stats.minutes_played }} minutes played</a>
    </div>

    <div class="w-full mt-5">
      <h3 class="font-medium text-gray-900 text-left px-6">RECENT GAMES</h3>
      <div class="mt-5 w-full flex flex-col items-center overflow-hidden text-sm">
        {% if latest_events or custom_events %}
          {% for event in latest_events %}
          <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
            <img src="https://avatars0.githubusercontent.com/u/35900628?v=4" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                {{ event.event_type }} in {{ event.match }}
                <span class="text-gray-500 text-xs">24 min ago</span>
          </a>
          {% endfor %}

          {% for event in custom_events %}
          <a href="#" class="w-full border-t border-gray-100 text-gray-600 py-4 pl-6 pr-3 w-full block hover:bg-gray-100 transition duration-150">
            <img src="https://avatars0.githubusercontent.com/u/35900628?v=4" alt="" class="rounded-full h-6 shadow-md inline-block mr-2">
                {{ event.event_type }} in {{ event.custom_match }}
                <span class="text-gray-500 text-xs">24 min ago</span>
          </a>
          {% endfor %}
        {% else %}
          <p class="font-medium text-gray-900 text-left px-6 mb-4">No recent games</p>
        {% endif %}
      </div>
    </div>
  </div>
</div>

<div class="flex justify-center mt-10 space-x-4">
  {% if is_coach_player %}
    {% comment %} <a href="{% url 'players:player-update-teams' player.slug %}">
      <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Update Teams
      </button>
    </a> {% endcomment %}

    <a href="{% url 'players:player-update' player.slug %}">
      <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
        Update Player Details
      </button>
    </a>

    <a href="{% url 'players:player-delete' player.slug %}">
      <button class="text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:outline-none focus:ring-red-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-800">
        Delete Player?
      </button>
    </a>
  {% endif %}
  <a href="{% url 'players:player-matches' player.slug%}">
    <button class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
      Player Games
    </button>
  </a>
</div>



{% endblock content %}

players/templates/players/player_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-6 mx-auto">
    <div class="flex flex-col text-center w-full mb-10">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Players</h1>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Players List</p>
    </div>

    <form class="max-w py-3 w-1/2">   
      <label for="default-search" class="mb-2 text-sm font-medium text-gray-900 sr-only text-white">Search</label>
      <div class="relative">
          <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
              <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
                  <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
              </svg>
          </div>
          <input type="text" id="search-box" class="block w-full p-4 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg bg-gray-50 focus:ring-gray-500 focus:border-gray-400 bg-gray-400 border-gray-500 placeholder-gray-800 text-black focus:ring-gray-500 focus:border-blue-500" placeholder="Search Players..." required name="search"
          hx-get="{% url 'players:player-list' %}"
          hx-trigger="keyup delay:500ms"
          hx-target="#players-list"/>
          <button type="submit" class="text-white absolute end-2.5 bottom-2.5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 bg-blue-600 dark:hover:bg-blue-700 focus:ring-blue-800" 
          >Search</button>
      </div>
    </form>

    <div id="players-list" class="lg:w-3/3 w-full mx-auto overflow-auto">
      {% include 'players/partials/partial_player_list.html' %}
    </div>
  </div>
</section>

{% endblock content %}

players/templates/players/player_update.html
{% extends "base.html" %} 
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
  <div class="flex justify-center mt-10">
    <a class="text-blue-800 hover:text-blue-500" href="{% url 'players:player-list'%}"> Back to players list</a>
  </div>

  <div class="flex justify-center py-5 border-gray-200">
    <h1 class="text-4xl text-gray-800">Update player details</h1>
  </div>

  <form method="post" class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
  </form>

</div>

{% endblock content %}

players/templates/players/player_update_teams.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class="">
    <div class="flex justify-center py-5 border-gray-200">
        <h1 class="text-4xl text-gray-800">Update Teams for {{ player.first_name }} {{ player.last_name }}</h1>
    </div>

    <div class="max-w-lg mx-auto">
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Save</button>
        </form>
        <div class="mt-2 mb-10 flex justify-center">
            <a href="{% url 'players:player-detail' player.slug %}" class="text-blue-800">Back to Player Detail</a>
        </div>
    </div>
</div>

{% endblock %}

players/templates/players/players_matches.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-10">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">
        Matches {{ player.first_name }} {{ player.last_name }} played in</h1>
    </div>

    <div class="lg:w-3/3 w-full mx-auto overflow-auto">
      <table class="table-auto w-full text-left whitespace-no-wrap">
        <thead>
          <tr>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Player Team</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Opposition's Team</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Scoreline</th>
            <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Date</th>
            <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
          </tr>
        </thead>
        {% for stat in stats %}
        <tbody>
          <tr>
          <td class="px-4 py-3">
              <a href="{% url 'matches:match-detail' stat.match.slug %}">
                  {{ stat.match.home_team }}
              </a>
          </td>
          <td class="px-4 py-3">
              <a href="{% url 'matches:match-detail' stat.match.slug %}">
                  {{ stat.match.away_team }}
              </a>
          </td>
          <td class="px-4 py-3">
              {{ stat.match.result.score_hometeam }} : {{ stat.match.result.score_awayteam }}</td>
          <td class="px-4 py-3 text-lg text-gray-900">{{ stat.match.match_date }}</td>
          <td class="px-4 py-3 text-lg text-gray-900">
            <a class="px-4 py-3 text-lg underline text-blue-900" href="{% url 'matches:match-detail' stat.match.slug %}">View</a>
          </td>
          </tr>
        </tbody>
        {% endfor %}

        {% if custom_qs %}
          {% for stat in custom_qs %}
          <tbody>
            <tr>
            <td class="px-4 py-3">
                <a href="{% url 'custommatches:custommatch-detail' stat.custom_match.slug %}">
                    {{ stat.custom_match.user_team }}
                </a>
            </td>
            <td class="px-4 py-3">
                <a href="{% url 'custommatches:custommatch-detail' stat.custom_match.slug %}">
                    {{ stat.custom_match.versus_team }}
                </a>
            </td>
            <td class="px-4 py-3">
                {{ stat.custom_match.custommatchresult.score_userteam }} : {{ stat.custom_match.custommatchresult.score_versusteam }}</td>
            <td class="px-4 py-3 text-lg text-gray-900">{{ stat.custom_match.match_date }}</td>
            <td class="px-4 py-3 text-lg text-gray-900">
              <a class="px-4 py-3 text-lg underline text-blue-900" href="{% url 'custommatches:custommatch-detail' stat.custom_match.slug %}">View</a>
            </td>
            </tr>
          </tbody>
          {% endfor %}
        {% endif %}
      </table>
    </div>

  </div>
</section>

{% endblock content %}