bifefootball/urls.py
from django.contrib import admin
from django.urls import path, include

from players.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path("matches/", include("matches.urls", namespace="matches")),
    path("admins/", include("admins.urls", namespace="admins")),
    path("players/", include("players.urls", namespace="players")),
    path("organizations/", include("organizations.urls", namespace="organizations")),
    path("teams/", include("teams.urls", namespace="teams")),
    path('accounts/', include('allauth.urls')),
    path("custommatches/", include("custommatches.urls", namespace="custommatches")),
]

custommatches/urls.py
from django.urls import path

from .views import CustomMatchCreateView, CustomMatchCreateEventView, CustomMatchDetailView, CustomResultCreateView, CustomMatchPlayerStatCreateEventView

"""
BASE ENDPOINT /custommatches
"""
app_name = "custommatches"

urlpatterns = [
    path("create/", CustomMatchCreateView.as_view(), name='custommatch-create'),
    path("custom-result/<slug:slug>", CustomResultCreateView.as_view(), name='custom-create-result'),
    path("custom-playerstat/<slug:slug>/", CustomMatchPlayerStatCreateEventView.as_view(), name='custom-playerstat-create'),
    path("custom-event/<slug:slug>/", CustomMatchCreateEventView.as_view(), name='custommatch-event-create'),
    path("<slug:slug>/", CustomMatchDetailView.as_view(), name='custommatch-detail'),
]

matches/urls.py
from django.urls import path
from .views import (
    MatchListView,
    MatchDetailView,
    MatchCreateView,
    MatchCreateEventView,
    ResultCreateView,
    PlayerStatCreateEventView,
    UpdateTeamsView,
    )

"""
BASE ENDPOINT /matches
"""
app_name = "matches"

urlpatterns = [
    path("", MatchListView.as_view(), name='match-list'),
    path("create/", MatchCreateView.as_view(), name='match-create'),
    path("create-event/<slug:slug>/", MatchCreateEventView.as_view(), name='match-event-create'),
    path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path('update-teams/', UpdateTeamsView.as_view(), name='update-teams'),
    path("create-playerstat/<slug:slug>/", PlayerStatCreateEventView.as_view(), name='player-stat-create'),
    path("<slug:slug>/", MatchDetailView.as_view(), name='match-detail'),
]

teams/urls.py
from django.urls import path
from .views import (
    TeamListView,
    TeamCreateView,
    TeamDetailView,
    TeamDashboardView,
    TeamMatchesView,
    CoachCreateView,
    TeamSelectView
    )

"""
BASE ENDPOINT /teams
"""
app_name = "teams"

urlpatterns = [
    path("", TeamListView.as_view(), name='team-list'),
    path("create/", TeamCreateView.as_view(), name='team-create'),
    path("create-coach/", CoachCreateView.as_view(), name='coach-create'),
    path('select-team/', TeamSelectView.as_view(), name='team-select'),
    path("team-dashboard/", TeamDashboardView.as_view(), name='team-dashboard'),
    # path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path("<slug:slug>/team-matches", TeamMatchesView.as_view(), name='team-matches'),
    path("<slug:slug>/", TeamDetailView.as_view(), name='team-detail'),
]

matches/models.py
from django.db import models

players/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from utils.generators import unique_slugify
import datetime


PLAYER_POSITION = (
    ("GK", "Goalkeeper"),
    ("CB", "Centre Back"),
    ("LCB", "Left Centre Back"),
    ("RCB", "Right Centre Back"),
    ("RB", "Right Back"),
    ("LB", "Left Back"),
    ("CM", "Center Midfield"),
    ("CDM", "Center Defensive Midfield"),
    ("CAM", "Center Attacking Midfield"),
    ("LAM", "Left Attacking Midfield"),
    ("RAM", "Right Attacking Midfield"),
    ("LWB", "Left Wing Back"),
    ("RWB", "Right Wing Back"),
    ("ST", "Striker"),
    ("CF", "Center Forward"),
    ("LW", "Left Wing"),
    ("RW", "Right Wing"),
    )

MINUTES_CHOICES = [(i, f"{i}'") for i in range(1, 121)]

EVENT_CHOICES = (
        ('GOAL', 'Goal'),
        ('ASSIST', 'Assist'),
        ('YELLOW_CARD', 'Yellow Card'),
        ('RED_CARD', 'Red Card'),
        ('SUBSTITUTION', 'Substitution'),
        ('HALFTIME', 'Halftime'),
        ('FULLTIME', 'Fulltime'),
    )


class User(AbstractUser):
    is_coach = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_player = models.BooleanField(default=False)


class Team(models.Model):
    team_name = models.CharField(max_length=80, unique=True)
    slug = models.SlugField(null=True, blank=True, unique=True)
    short_team_name = models.CharField(unique=True, max_length=3)
    team_description = models.TextField(default="No description")
    organisation = models.ForeignKey("User",
        on_delete=models.CASCADE,
        related_name='team'
    ) # remember to filter for one organisation, a user can have multiple teams

    def __str__(self):
        return self.team_name
    
    def save(self, *args, **kwargs):
        new_slug = f"{self.team_name}"
        unique_slugify(self, new_slug)
        super().save(*args, **kwargs)
    

class Coach(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    role = models.CharField(max_length=20, default="Assistant Coach")
    team = models.ForeignKey("Team", on_delete=models.CASCADE, related_name='coach')
    user = models.OneToOneField("User", on_delete=models.CASCADE)


    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Player(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    shirt_number = models.IntegerField()
    slug = models.SlugField(null=True, blank=True, unique=True)
    age = models.IntegerField(default=0)
    teams = models.ManyToManyField("Team", through="Contract")
    matches = models.ManyToManyField("Match", through="PlayerStat")
    position = models.CharField(max_length=30, blank=True, choices=PLAYER_POSITION)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
    def save(self, *args, **kwargs):
        new_slug = f"{self.first_name} {self.last_name}"
        unique_slugify(self, new_slug)
        super().save(*args, **kwargs)
    

class PlayerStat(models.Model):
    player = models.ForeignKey("Player", related_name="stats", on_delete=models.CASCADE)
    player_contract = models.ForeignKey("Contract", related_name="stats", on_delete=models.CASCADE)
    match = models.ForeignKey("Match", on_delete=models.CASCADE)
    goals = models.IntegerField()
    assists = models.IntegerField()
    minutes_played = models.IntegerField(choices=MINUTES_CHOICES)
    rating = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        unique_together = ['player_contract', 'match']

    def __str__(self):
        return f"{self.player} in {self.match}"
    

class Venue(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return f"{self.name}"


class Match(models.Model):
    home_team = models.ForeignKey("Team", related_name='home_matches', on_delete=models.CASCADE)
    away_team = models.ForeignKey("Team", related_name='away_matches', on_delete=models.CASCADE)
    venue = models.CharField(max_length=20, blank=False, null=False)
    match_date = models.DateTimeField()
    slug = models.SlugField(null=True, blank=True, unique=True)
    is_fixture = models.BooleanField(default=True)
    has_result = models.BooleanField(default=False)

    class Meta:
        unique_together = ['home_team', 'away_team', 'match_date']
        ordering = ['match_date']    

    def save(self, *args, **kwargs):
        new_slug = f"{self.home_team} vs {self.away_team}"
        unique_slugify(self,new_slug)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.home_team} ({self.home_team.short_team_name}) vs {self.away_team} ({self.away_team.short_team_name})"


class Result(models.Model):
    match = models.OneToOneField("Match", on_delete=models.CASCADE)
    score_hometeam = models.IntegerField()
    score_awayteam = models.IntegerField()

    def __str__(self):
        return f"{self.match}: {self.score_hometeam} - {self.score_awayteam}"
    

class Contract(models.Model):
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    team = models.ForeignKey("Team", on_delete=models.CASCADE)
    contract_date = models.DateField(default=datetime.date.today)
    is_valid = models.BooleanField(default=True)
    
    class Meta:
        unique_together = ['player', 'team', 'contract_date']
        ordering = ['-contract_date']

    def __str__(self):
        return f"{self.player} for {self.team.short_team_name}"


class MatchEvent(models.Model):
    match = models.ForeignKey('Match', on_delete=models.CASCADE, related_name='match_events')
    event_type = models.CharField(max_length=20, choices=EVENT_CHOICES)
    timestamp = models.DateTimeField(auto_now_add=True)
    minute = models.PositiveSmallIntegerField(choices=MINUTES_CHOICES)
    player_contract = models.ForeignKey('Contract', on_delete=models.CASCADE, null=True, blank=True)
    related_player = models.ForeignKey('Contract', on_delete=models.CASCADE, null=True, blank=True, related_name='related_events')
    is_own_goal = models.BooleanField(default=False)
    is_penalty = models.BooleanField(default=False)
    is_second_yellow_card = models.BooleanField(default=False)
    is_direct_red_card = models.BooleanField(default=False)

    class Meta:
        ordering = ['minute']

    def __str__(self):
        return f"{self.event_type} - Match: {self.match}"
    
    def save(self, *args, **kwargs):
        # Check for and delete previous duplicates
        MatchEvent.objects.filter(match=self.match, minute=self.minute, player_contract=self.player_contract, event_type=self.event_type).delete()
        # Save the new instance
        super().save(*args, **kwargs)
    

matches/forms.py
from django import forms
from django.conf import settings
from django import forms
from django.forms.models import inlineformset_factory, BaseInlineFormSet
from django.db.models import Q

from players.models import Match, MatchEvent, PlayerStat, Contract, Team
from .widgets import DateTimePickerInput


GET_LATEST_CONTRACTS = settings.GET_LATEST_CONTRACTS


class MatchModelForm(forms.ModelForm):
    class Meta:
        model = Match
        fields = ("home_team", "away_team", "venue", "match_date")
        widgets = {
            "match_date": DateTimePickerInput(attrs={'type': 'datetime-local', 'class': 'form-input'}),
            "home_team": forms.Select(attrs={'class': 'form-select'}),
            "away_team": forms.Select(attrs={'class': 'form-select'}),
        }

    def __init__(self, *args, **kwargs):
        user_team = kwargs.pop('user_team', None)
        match_type = kwargs.pop('match_type', 'home')
        super(MatchModelForm, self).__init__(*args, **kwargs)
        if user_team:
            if match_type == 'home':
                self.fields['home_team'].queryset = Team.objects.filter(id=user_team.id)
                self.fields['away_team'].queryset = Team.objects.exclude(id=user_team.id)
            else:
                self.fields['home_team'].queryset = Team.objects.exclude(id=user_team.id)
                self.fields['away_team'].queryset = Team.objects.filter(id=user_team.id)


class MatchEventModelForm(forms.ModelForm):
    class Meta:
        model = MatchEvent
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        slug = kwargs.pop('slug')
        match = Match.objects.get(slug=slug)

        contract_for_teams = Contract.objects.filter(Q(is_valid=True) & (Q(team=match.home_team) | Q(team=match.away_team)))
        latest_contracts = contract_for_teams.extra(
            where=[GET_LATEST_CONTRACTS]
        )
        super(MatchEventModelForm, self).__init__(*args, **kwargs)
        self.fields["player_contract"].queryset = latest_contracts
        self.fields["related_player"].queryset = latest_contracts

        # for field_name in self.fields:
        #     if field_name == "player_contract":
        #         self.fields[field_name].required = True


MatchEventFormSet = inlineformset_factory(
    Match, MatchEvent, form=MatchEventModelForm, extra=1, can_delete=False)


class PlayerStatModelForm(forms.ModelForm):
    class Meta:
        model = PlayerStat
        fields = ("player_contract", "goals", "assists", "minutes_played", "rating")

    def __init__(self, *args, **kwargs):
        match = Match.objects.get(slug=kwargs.pop("slug"))
        # Filter for players that have signed a contract for each team
        # Then filter for the latest contract for each players
        contract_for_teams = Contract.objects.filter(Q(is_valid=True) & (Q(team=match.home_team) | Q(team=match.away_team)))
        latest_contracts = contract_for_teams.extra(
            where=[GET_LATEST_CONTRACTS]
        )
        super(PlayerStatModelForm, self).__init__(*args, **kwargs)
        self.fields["player_contract"].queryset = latest_contracts
        self.fields["player_contract"].disabled = True

        for field_name in self.fields:
            self.fields[field_name].required = True

    @staticmethod
    def get_latest_contracts(match):
        contract_for_teams = Contract.objects.filter(Q(is_valid=True) & (Q(team=match.home_team) | Q(team=match.away_team)))
        return contract_for_teams.extra(
            where=[GET_LATEST_CONTRACTS]
        )
        # Contract.objects.filter(
        #     Q(is_valid=True) & 
        #     (Q(team=match.home_team) | Q(team=match.away_team))
        # ).order_by('player', '-date_signed').distinct('player')


class BasePlayerStatFormSet(BaseInlineFormSet):
    def __init__(self, *args, **kwargs):
        self.match = kwargs['instance']
        self.player_contracts = PlayerStatModelForm.get_latest_contracts(self.match)
        self.extra = len(self.player_contracts)
        super(BasePlayerStatFormSet, self).__init__(*args, **kwargs)
        for form, contract in zip(self.forms, self.player_contracts):
            form.initial['player_contract'] = contract


PlayerStatFormSet = inlineformset_factory(
    Match, PlayerStat, form=PlayerStatModelForm, formset=BasePlayerStatFormSet, extra=0, can_delete=False)

matches/templates/matches/match_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class="container p-4 mx-auto">
  <div class="flex justify-center mt-5 mb-5">
    <a class="hover:text-blue-500 mt-3" href="{% url 'matches:match-list'%}"> Go back to match list</a>
  </div>

  <div class="flex justify-center">
    <h1 class="text-2xl font-bold">Create a new match</h1>
  </div>

  <div class="flex justify-center">
    <h1 class="text-l mb-4">This is for creating matches against teams that use this platform, for custom opponents use 
      <a href="{% url 'custommatches:custommatch-create' %}" class="text-blue-500"> this </a> </h1>
  </div>

  <div class="max-w-lg mx-auto mb-3">
    <label for="team_id" class="block text-sm font-medium text-black">Select Team:</label>
    <div class="mt-1">
      <select name="team_id" id="team_id" class="form-select block w-full pl-3 pr-10 py-2 text-base border-gray-300 rounded-md" hx-get="{% url 'matches:update-teams' %}" hx-target="#team-fields" hx-trigger="change">
        {% for team in user_teams %}
          <option value="{{ team.id }}" {% if team == user_team %}selected{% endif %}>{{ team.team_name }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  
  <form method="post" class="max-w-sm mx-auto">
    {% csrf_token %}
    <label>
      <input type="radio" name="match_type" id="home" value="home" {% if match_type == 'home' %}checked{% endif %} hx-get="{% url 'matches:update-teams' %}" hx-trigger="change" hx-target="#team-fields"> Home Game
    </label>
    <label>
      <input type="radio" name="match_type" id="away" value="away" {% if match_type == 'away' %}checked{% endif %} hx-get="{% url 'matches:update-teams' %}" hx-trigger="change" hx-target="#team-fields"> Away Game
    </label>

    <div id="team-fields" hx-swap="innerHTML">
      {% include 'matches/partials/team_fields.html' %}
    </div>
    
    <div class="mb-4">
      <label for="id_venue" class="block text-gray-700 text-sm font-bold mb-2">{% comment %}Venue{% endcomment %}</label>
      {{ form.venue|as_crispy_field }}
    </div>
    <div class="mb-4">
      <label for="id_match_date" class="block text-gray-700 text-sm font-bold mb-2">{% comment %}Match Date{% endcomment %}</label> 
      {{ form.match_date|as_crispy_field }}
    </div>

    <div class="mt-6">
      <button type="submit" class="w-full bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">
        Save Match
      </button>
    </div>
  </form>

  <script>
    document.addEventListener('DOMContentLoaded', function() {
      document.getElementById('team_id').addEventListener('change', function() {
        document.getElementById('home').checked = true;
      });
    });
  </script>

</div>

{% endblock content %}

matches/templates/matches/match_detail.html
{% extends "base.html" %}

{% block content %}
<section class="container mx-auto p-6 font-mono">
  <div class="flex flex-col text-center w-full mb-10">
    <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Match Details</h1>
    {% if match.has_result %}
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base">{{ match.result }}</p>
    {% endif %}
  </div>

  {% if can_edit_stats %}
  <div class="flex justify-left mb-2">
    {% if not match.is_fixture and not match.has_result %}
      <a href="{% url 'matches:result-create' match.slug %}" class="mr-5">
        <p class="inline-flex text-white bg-blue-500 border-0 py-2 px-2 focus:outline-none hover:bg-blue-600 rounded text-sm">CONFIRM RESULTS!</p>
      </a>
    {% elif match.is_fixture %}
      <a href="{% url 'matches:match-event-create' match.slug %}" class="mr-5">
        <p class="inline-flex text-white bg-blue-500 border-0 py-2 px-2 focus:outline-none hover:bg-blue-600 rounded text-sm">Add Match Events</p>
      </a>
    {% endif %}
      <a href="{% url 'matches:player-stat-create' match.slug %}">
        <p class="inline-flex text-white bg-blue-500 border-0 py-2 px-2 focus:outline-none hover:bg-blue-600 rounded text-sm">Edit or Add Player Stats</p>
      </a>
  </div>
  {% endif %}

  
  <p class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Home Team - {{ match.home_team }}</p>
  <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
    <div class="w-full overflow-x-auto">
      <table class="w-full">
        <thead>
          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Age</th>
            <th class="px-4 py-3">Rating</th>
            <th class="px-4 py-3">Minutes played</th>
          </tr>
        </thead>
        {% for player_stat in hometeam_players %}
          <tbody class="bg-white">
            <tr class="text-gray-700">
              <td class="px-4 py-3 border">
                <div class="flex items-center text-sm">
                  <div>
                    <p class="font-semibold text-black">
                      {{ player_stat.player.first_name}} {{ player_stat.player.last_name}}
                    </p>
                    <p class="text-xs text-gray-600">{{ player_stat.player.position}}</p>
                  </div>
                </div>
              </td>
              <td class="px-4 py-3 text-ms font-semibold border">{{ player_stat.player.age }}</td>
              <td class="px-4 py-3 text-xs border">
                <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm"> {{ player_stat.rating }} </span>
              </td>
              <td class="px-4 py-3 text-sm border">{{ player_stat.minutes_played }}</td>
            </tr>
          </tbody>
        {% endfor %}
      </table>
    </div>
  </div>

  <p class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Away Team - {{ match.away_team }}</p>
  <div class="w-full mb-8 overflow-hidden rounded-lg shadow-lg">
    <div class="w-full overflow-x-auto">
      <table class="w-full">
        <thead>
          <tr class="text-md font-semibold tracking-wide text-left text-gray-900 bg-gray-100 uppercase border-b border-gray-600">
            <th class="px-4 py-3">Name</th>
            <th class="px-4 py-3">Age</th>
            <th class="px-4 py-3">Rating</th>
            <th class="px-4 py-3">Minutes played</th>
          </tr>
        </thead>
        {% for player_stat in awayteam_players %}
          <tbody class="bg-white">
            <tr class="text-gray-700">
              <td class="px-4 py-3 border">
                <div class="flex items-center text-sm">
                  <div>
                    <p class="font-semibold text-black">{{ player_stat.player.first_name}}
                        {{ player_stat.player.last_name}}
                    </p>
                    <p class="text-xs text-gray-600">{{ player_stat.player.position}}</p>
                  </div>
                </div>
              </td>
              <td class="px-4 py-3 text-ms font-semibold border">{{ player_stat.player.age }}</td>
              <td class="px-4 py-3 text-xs border">
                <span class="px-2 py-1 font-semibold leading-tight text-green-700 bg-green-100 rounded-sm"> {{ player_stat.rating }} </span>
              </td>
              <td class="px-4 py-3 text-sm border">{{ player_stat.minutes_played }}</td>
            
            </tr>
          </tbody>
        {% endfor %}
      </table>
    </div>
  </div>

  <div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">MATCH EVENTS</h1>
  </div>
  {% if events %}
    <div class="px-5 lg:w-3/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Event type</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Player</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Minute</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Related player</th>
            </tr>
          </thead>
          {% for event in events %}
          <tbody>
            <tr>
            <td class="px-4 py-3 rounded-tl rounded-bl">{{ event.event_type }}</td>
            <td class="px-4 py-3 rounded-tl rounded-bl">{{ event.player_contract }}</td>
            <td class="px-4 py-3 rounded-tl rounded-bl">{{ event.minute }}'</td>
            <td class="px-4 py-3 rounded-tl rounded-bl">{{ event.related_player }}</td>
            </tr>
          </tbody>
          {% endfor %}
        </table>
    </div>
  {% else %}
    <div class="flex flex-col text-center w-full mb-10">
      <p class="lg:w-2/3 mx-auto leading-relaxed text-base font-semibold">
      NONE AT THIS TIME...</p>
    </div>  
  {% endif %}
    
</section>
  
{% endblock content %}

matches/templates/matches/search_match_list.html
<div class="lg:w-3/3 w-full mx-auto overflow-auto">
  <div class="flex flex-col w-full mb-5">
    <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Results</h1>
  </div>

  <table class="table-auto w-full text-left whitespace-no-wrap">
    <thead>
      <tr>
        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Home team</th>
        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Away team</th>
        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Scoreline</th>
        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Date</th>
        <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
      </tr>
    </thead>
    {% for result in results %}
    <tbody>
      <tr>
      <td class="px-4 py-3">
          <a href="{% url 'matches:match-detail' result.match.slug %}">
              {{ result.match.home_team }}
          </a>
      </td>
      <td class="px-4 py-3">
          <a href="{% url 'matches:match-detail' result.match.slug %}">
              {{ result.match.away_team }}
          </a>
      </td>
      <td class="px-4 py-3">
          {{ result.score_hometeam }} : {{ result.score_awayteam }}</td>
      <td class="px-4 py-3 text-lg text-gray-900">{{ result.match.match_date|date:"F d, Y, h:i A" }}</td>
      <td class="px-4 py-3 text-lg underline text-blue-900">
        <a href="{% url 'matches:match-detail' result.match.slug %}">View</a>
      </td>
      </tr>
    </tbody>
    {% endfor %}
  </table>
</div>

{% if fixtures %}
  <div class="lg:w-3/3 w-full mx-auto mb-10 overflow-auto">
    <div class="flex flex-col w-full mt-20 mb-5">
      <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Fixtures</h1>
    </div>
    <table class="table-auto w-full text-left whitespace-no-wrap">
      <thead>
        <tr>
          <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Home team</th>
          <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Away team</th>
          <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Date</th>
          <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
        </tr>
      </thead>
      {% for fixture in fixtures %}
      <tbody>
        <tr>
        <td class="px-3 py-3">
            <a href="{% url 'matches:match-detail' fixture.slug %}">
                {{ fixture.home_team }}
            </a>
        </td>
        <td class="px-3 py-3">
            <a href="{% url 'matches:match-detail' fixture.slug %}">
                {{ fixture.away_team }}
            </a>
        </td>
        <td class="px-3 py-3 text-lg text-gray-900">{{ fixture.match_date|date:"F d, Y, h:i A" }}</td>
        <td class="px-3 py-3 text-right text-lg underline text-blue-900">
          <a href="{% url 'matches:match-event-create' fixture.slug %}">Add event(s)</a>
        </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>
  </div>
{% endif %}