bifefootball/urls.py
from django.contrib import admin
from django.urls import path, include

from players.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path("matches/", include("matches.urls", namespace="matches")),
    path("admins/", include("admins.urls", namespace="admins")),
    path("players/", include("players.urls", namespace="players")),
    path("organizations/", include("organizations.urls", namespace="organizations")),
    path("teams/", include("teams.urls", namespace="teams")),
    path('accounts/', include('allauth.urls')),
    path("custommatches/", include("custommatches.urls", namespace="custommatches")),
]

custommatches/urls.py
from django.urls import path

from .views import CustomMatchCreateView, CustomMatchCreateEventView, CustomMatchDetailView, CustomResultCreateView, CustomMatchPlayerStatCreateEventView

"""
BASE ENDPOINT /custommatches
"""
app_name = "custommatches"

urlpatterns = [
    path("create/", CustomMatchCreateView.as_view(), name='custommatch-create'),
    path("custom-result/<slug:slug>", CustomResultCreateView.as_view(), name='custom-create-result'),
    path("custom-playerstat/<slug:slug>/", CustomMatchPlayerStatCreateEventView.as_view(), name='custom-playerstat-create'),
    path("custom-event/<slug:slug>/", CustomMatchCreateEventView.as_view(), name='custommatch-event-create'),
    path("<slug:slug>/", CustomMatchDetailView.as_view(), name='custommatch-detail'),
]

matches/urls.py
from django.urls import path
from .views import (
    MatchListView,
    MatchDetailView,
    MatchCreateView,
    MatchCreateEventView,
    ResultCreateView,
    PlayerStatCreateEventView,
    UpdateTeamsView,
    )

"""
BASE ENDPOINT /matches
"""
app_name = "matches"

urlpatterns = [
    path("", MatchListView.as_view(), name='match-list'),
    path("create/", MatchCreateView.as_view(), name='match-create'),
    path("create-event/<slug:slug>/", MatchCreateEventView.as_view(), name='match-event-create'),
    path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path('update-teams/', UpdateTeamsView.as_view(), name='update-teams'),
    path("create-playerstat/<slug:slug>/", PlayerStatCreateEventView.as_view(), name='player-stat-create'),
    path("<slug:slug>/", MatchDetailView.as_view(), name='match-detail'),
]

players/urls.py
from django.urls import path
from .views import (
    PlayerListView,
    PlayerDetailView,
    PlayerCreateView,
    PlayerUpdateView,
    PlayerDeleteView,
    PlayerMatchesListView,
    PlayerUpdateTeamsView,
    TeamSelectView,
    )

"""
BASE ENDPOINT /players
"""
app_name = "players"

urlpatterns = [
    path("", PlayerListView.as_view(), name='player-list'),
    path("create/", PlayerCreateView.as_view(), name='player-create'),
    path('select-team/', TeamSelectView.as_view(), name='team-select'),
    path("<slug:slug>/", PlayerDetailView.as_view(), name='player-detail'),
    path("<slug:slug>/update", PlayerUpdateView.as_view(), name='player-update'),
    path('<slug:slug>/update-teams/', PlayerUpdateTeamsView.as_view(), name='player-update-teams'),
    path("<slug:slug>/delete", PlayerDeleteView.as_view(), name='player-delete'),
    path("<slug:slug>/matches", PlayerMatchesListView.as_view(), name='player-matches'),
]

teams/urls.py
from django.urls import path
from .views import (
    TeamListView,
    TeamCreateView,
    TeamDetailView,
    TeamDashboardView,
    TeamMatchesView,
    CoachCreateView,
    TeamSelectView
    )

"""
BASE ENDPOINT /teams
"""
app_name = "teams"

urlpatterns = [
    path("", TeamListView.as_view(), name='team-list'),
    path("create/", TeamCreateView.as_view(), name='team-create'),
    path("create-coach/", CoachCreateView.as_view(), name='coach-create'),
    path('select-team/', TeamSelectView.as_view(), name='team-select'),
    path("team-dashboard/", TeamDashboardView.as_view(), name='team-dashboard'),
    # path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path("<slug:slug>/team-matches", TeamMatchesView.as_view(), name='team-matches'),
    path("<slug:slug>/", TeamDetailView.as_view(), name='team-detail'),
]

teams/forms.py
from django.core.exceptions import ValidationError
from django import forms


from players.models import Team, Player, Coach, User


class TeamModelForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"


class CoachModelForm(forms.ModelForm):
    username = forms.CharField(max_length=20, required=True, label="Coach's Username")
    email = forms.CharField(max_length=45, required=True, label="Email")

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise ValidationError('User with this email already exists.')
        return email
    
    class Meta:
        model = Coach
        fields = ("first_name", "last_name", "role")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(CoachModelForm, self).__init__(*args, **kwargs)


class TeamSelectForm(forms.Form):
    team = forms.ModelChoiceField(queryset=Team.objects.all(), required=True, label="Select Team")

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(TeamSelectForm, self).__init__(*args, **kwargs) 
        # Check if obj is an instance of the Player or Coach model       
        if hasattr(user, 'player'):
            self.fields['team'].queryset = user.player.teams.filter(contract__is_valid=True)
        if hasattr(user, 'coach'):
            self.fields['team'].queryset = Team.objects.filter(slug=user.coach.team.slug)

teams/views.py
import random
from typing import Any
# from django.db.models.query import QuerySet
from django.db.models import Subquery
from django.shortcuts import render, reverse, get_object_or_404, redirect
from django.conf import settings
from django.db.models import Sum
from utils.titlecase import titlecase
from faker import Faker
from django.contrib import messages
from django.views import generic
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin

from allauth.account.utils import send_email_confirmation
from players.mixins import AdminorCoachRequiredMixin, AdminRequiredMixin
from .forms import TeamModelForm, TeamSelectForm, CoachModelForm
from players.models import Team, Contract, Match, Player, Result, PlayerStat, User
from admins.models import Admin
from custommatches.models import CustomMatch, CustomMatchResult, CustomMatchPlayerStat

GET_LATEST_CONTRACTS = settings.GET_LATEST_CONTRACTS


class TeamListView(generic.ListView):
    template_name = "teams/team_list.html"
    paginate_by = 10
    context_object_name = "teams"

    def get_queryset(self):
        return Team.objects.all().order_by('id')
    
    def get(self, request, *args, **kwargs):
        search = request.GET.get('search')
        qs = self.get_queryset()
        if search:
            qs = self.get_queryset().filter(Q(team_name__icontains=search) | Q(short_team_name__icontains=search))

        paginator = Paginator(qs, 15)
        page_number = request.GET.get("page")
        page_obj = paginator.get_page(page_number)

        if request.htmx:
            return render(request, 'teams/partials/partial_team_list.html', {'page_obj': page_obj})
        else:
            return render(request, 'teams/team_list.html', {'page_obj': page_obj})


class TeamCreateView(AdminRequiredMixin, generic.CreateView):
    template_name = "teams/team_create.html"
    form_class = TeamModelForm

    def get_success_url(self):
        return reverse("team:team-list")
    
    def form_valid(self, form):
        return super(TeamCreateView, self).form_valid(form)


class TeamDetailView(generic.DetailView):
    template_name = "teams/team_detail.html"
    context_object_name = "team"

    def get_queryset(self):
        return Team.objects.all()
    
    def get_context_data(self, **kwargs):
        context = super(TeamDetailView, self).get_context_data(**kwargs)
        contract = Contract.objects.filter(team=self.get_object(), is_valid=True).order_by('-contract_date')
        latest_contracts = contract.extra(
            where=[GET_LATEST_CONTRACTS]
        )
        upcoming_matches = Match.objects.filter(Q(home_team=self.get_object()) | Q(away_team=self.get_object()), is_fixture=True).order_by('-match_date')[:5]
        custom_matches = CustomMatch.objects.filter(Q(user_team=self.get_object()), is_fixture=True).order_by('-match_date')[:5]

        team_results = Result.objects.filter(Q(match__home_team=self.get_object()) | Q(match__away_team=self.get_object())).order_by('-match__match_date')[:5]
        custom_results = CustomMatchResult.objects.filter(Q(custom_match__user_team=self.get_object())).order_by('-custom_match__match_date')[:5]

        context.update({
            "contracts": latest_contracts,
            "upcoming_matches": upcoming_matches,
            "custom_matches": custom_matches,
            "custom_results": custom_results,
            "team_results": team_results,
            "selected_team": self.get_object()
        })

        return context


class TeamDashboardView(LoginRequiredMixin, AdminorCoachRequiredMixin, generic.DetailView):
    model = Player
    template_name = "teams/team_dashboard.html"
    context_object_name = "team"

    def get_object(self):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        self.ensure_default_team_in_session(user)
        selected_team_id = self.request.session.get('selected_team_id')

        if hasattr(user, 'player'):
            selected_team = self.get_valid_team(user.player.teams, selected_team_id)
        elif hasattr(user, 'coach'):
            selected_team = user.coach.team

        
        form = TeamSelectForm(user=user, initial={'team': selected_team})
        # team_stats = player.playerstat_set.filter(team=selected_team)
        
        context.update(self.get_dashboard_context(form, selected_team))
        return context
    
    def ensure_default_team_in_session(self, user):
        if 'selected_team_id' not in self.request.session:
            if hasattr(user, 'player'):
                first_team = user.player.teams.first()
            elif hasattr(user, 'coach'):
                first_team = user.coach.team
            self.request.session['selected_team_id'] = first_team.id
    
    def get_valid_team(self, teams, selected_team_id):
        # Ensure the selected team exists and belongs to the user
        if selected_team_id:
            selected_team = teams.filter(id=selected_team_id).first()
            if selected_team:
                return selected_team
        # Default to the first team if the selected team is invalid
        return teams.first()
    
    def group_stats(self, stats, queryset, is_custom):
        for stat in queryset:
            if is_custom:
                match_slug = stat.custom_match.slug
            else:
                match_slug = stat.match.slug
            if match_slug not in stats:
                if is_custom:
                    match = stat.custom_match
                else:
                    match = stat.match
                stats[match_slug] = {
                    'match': match,
                    'player_stats': []
                }
            stats[match_slug]['player_stats'].append(stat)
        
        return stats
    
    def get_dashboard_context(self, form, selected_team):
        contract = Contract.objects.filter(team=selected_team, is_valid=True).order_by('-contract_date')
        latest_contracts = contract.extra(where=[GET_LATEST_CONTRACTS])

        # MATCHES
        all_matches = Match.objects.filter(Q(home_team=selected_team) | Q(away_team=selected_team), is_fixture=True)
        all_results = Result.objects.filter(Q(match__home_team=selected_team) | Q(match__away_team=selected_team))

        # CUSTOM MATCHES
        all_custom_matches = CustomMatch.objects.filter(Q(user_team=selected_team),is_fixture=True)
        all_custom_results = CustomMatchResult.objects.filter(Q(custom_match__user_team=selected_team))


        upcoming_matches = all_matches.order_by('match_date')[:5]
        team_results = all_results.order_by('-match__match_date')[:5]
        custom_matches = all_custom_matches.order_by('match_date')[:5]
        custom_results = all_custom_results.order_by('-custom_match__match_date')[:5]

        player_stats = PlayerStat.objects.filter(match__in=Subquery(team_results.values("match")[:3]), player_contract__team=selected_team)
        custom_player_stats = CustomMatchPlayerStat.objects.filter(custom_match__in=Subquery(custom_results.values("custom_match")[:3]), player_contract__team=selected_team)

        # Group player stats by match
        matches_stats = {}
        matches_stats = self.group_stats(matches_stats, player_stats, False)
        matches_stats = self.group_stats(matches_stats, custom_player_stats, True)

        home_goals = Result.objects.filter(match__home_team=selected_team).aggregate(total=Sum('score_hometeam'))['total'] or 0
        away_goals = Result.objects.filter(match__away_team=selected_team).aggregate(total=Sum('score_awayteam'))['total'] or 0
        goals_in_custom = CustomMatchResult.objects.filter(custom_match__user_team=selected_team).aggregate(total=Sum('score_userteam'))['total'] or 0

        goals_scored = home_goals + away_goals + goals_in_custom

        return {
            "contracts": latest_contracts,
            "upcoming_matches": upcoming_matches,
            "custom_matches": custom_matches,
            "goals_scored": goals_scored,
            "games_played": all_results.count() + all_custom_results.count(),
            "games_to_play": all_custom_matches.count() + all_matches.count(),
            "team_results": team_results,
            "custom_results": custom_results,
            "selected_team": selected_team,
            "form": form,
            "matches_stats": matches_stats.values()
            # "team_stats": team_stats
        }
    
    
    def post(self, request, *args, **kwargs):
        user = self.get_object()
        form = TeamSelectForm(request.POST, user=user)
        if form.is_valid():
            selected_team = form.cleaned_data['team']
            # Save the selected team in the session
            self.request.session['selected_team_id'] = selected_team.id
        else:
            if hasattr(user, 'player'):
                selected_team = self.get_valid_team(user.player.teams, None)
            if hasattr(user, 'player'):
                selected_team = user.coach.team
        
        # team_stats = player.playerstat_set.filter(team=selected_team)

        if request.headers.get('HX-Request'):
            return render(request, 'teams/partials/partial_team_dashboard.html', self.get_dashboard_context(form, selected_team))
        else:
            context = self.get_context_data()
            context.update(self.get_dashboard_context(form, selected_team))
            return self.render_to_response(context)
        

class TeamMatchesView(LoginRequiredMixin, AdminorCoachRequiredMixin, generic.DetailView):
    template_name = "teams/team_matches.html"
    context_object_name = "team"

    def get_queryset(self):
        return Team.objects.filter(slug=self.kwargs['slug'])
    
    
    def get_context_data(self, **kwargs):
        context = super(TeamMatchesView, self).get_context_data(**kwargs)

teams/templates/teams/coach_create.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% block content %}

<div class="max-w-lg mx-auto">
  <div class="flex justify-center mt-10">
    <a class="text-blue-800" href="{% url 'teams:team-dashboard'%}">Back to Dashboard</a>
  </div>

  <div class="flex justify-center py-5 border-gray-200">
    <h1 class="text-4xl text-gray-800">Create a coach for your team</h1>
  </div>

  <div class="max-w-lg mx-auto mb-3">
    <form id="team-select-form" method="post" action="{% url 'teams:team-select' %}" class="mt-5">
      {% csrf_token %}
      <label for="team" class="block text-sm font-medium text-black">Select Team:</label>
      <div class="mt-1">
        <select id="team" class="form-select block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 rounded-md" name="team" onchange="document.getElementById('team-select-form').submit();">
          {% for team in admin_teams %}
            <option value="{{ team.id }}" {% if team.id == admin_team_id or forloop.first %}selected{% endif %}>{{ team.team_name }}</option>
          {% endfor %}
        </select>
      </div>
    </form>
  </div>

  <form method="post"class="mt-5">
    {% csrf_token %} {{ form|crispy }}
    <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md mb-10">Submit</button>
    </form>
  </form>

</div>

{% endblock content %}

teams/templates/teams/search_teamlist.html
<div id="fixture-list" class="lg:w-3/3 w-full mx-auto overflow-auto">
    <table class="table-auto w-full text-left">
      <thead>
        <tr>
          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Team</th>
          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Short name</th>
          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Coach</th>
          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Organisation</th>
          <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
        </tr>
      </thead>
      {% for team in page_obj %}
      <tbody>
        <tr>
        <td class="px-4 py-3">
            <a href="{% url 'teams:team-detail' team.pk %}">{{ team.team_name }}
            </a>
        </td>
        <td class="px-4 py-3">
            <a href="#">{{ team.short_team_name }}
            </a>
        </td>
        <td class="px-4 py-3">{{ team.coach.first }}</td>
        <td class="px-4 py-3 text-lg text-gray-900">{{ team.organisation }}</td>
        <td class="px-4 py-3 text-right text-lg underline text-blue-900">
          <a href="{% url 'teams:team-detail' team.pk %}">View team</a>
        </td>
        </tr>
      </tbody>
      {% endfor %}
    </table>

    <div class="pagination my-4 text-center">
        <span class="step-links">
            {% if page_obj.has_previous %}
            <div class="text-blue-700">
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            </div>
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
            <div>
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
            </div>
        </span>
    </div>
</div>

teams/templates/teams/team_create.html
{% extends "base.html" %} 
{% block content %}

<div class="max-w-lg mx-auto">
  <a class="hover:text-blue-500 mt-3" href="{% url 'teams:team-list'%}"> Go back to team list</a>

  <div class="py-5 border-t border-gray-200">
    <h1 class="text-4xl text-gray-800">Create a new team</h1>
  </div>

  <form method="post" class="">
    {% csrf_token %} 
    {{ form.as_p }}

    <button type="submit" class="w-full mt-5 text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
  </form>

</div>

{% endblock content %}

teams/templates/teams/team_detail.html
{% extends "base.html" %} 
{% block content %}

{% comment %} List of current squad players,
previous 10 results, upcoming fixtures
{% endcomment %}

<section class="text-gray-600 body-font">
    <div class="container px-5 py-10 mx-auto">
        <div class="flex flex-col text-center w-full mb-10 mt-10">
            <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-gray-900">{{ team.team_name }} - {{ team.short_team_name }}</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base font-semibold"> {{team.team_description }} </p>
        </div>

        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-5 text-gray-900">Squad</h1>
        <div class="flex flex-wrap -m-2">
            {% for contract in contracts %}
            <div class="p-2 lg:w-1/3 md:w-1/2 w-full">
            <div class="h-full flex items-center border-2 border-blue-800 p-4 rounded-lg">
                <img alt="team" class="w-16 h-16 bg-gray-100 object-cover object-center flex-shrink-0 rounded-full mr-8" src="https://dummyimage.com/80x80">
                <a href="{% url 'players:player-detail' contract.player.slug %}">
                    <div class="flex-grow">
                    <h2 class="text-gray-900 title-font font-medium">
                        {{ contract.player }}</h2>
                    <p class="text-gray-500">{{ contract.player.position }}</p>
                    </div>
                </a>
            </div>
            </div>
            {% endfor %}
        </div>

        <h1 class="sm:text-4xl text-3xl font-medium title-font mt-10 text-gray-900">Fixtures</h1>
        {% if upcoming_matches or custom_matches %}
            <div class="lg:w-3/3 w-full mx-auto mb-10 overflow-auto">
                <div class="flex flex-col w-full mb-5">
                </div>
                <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                    <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Home team</th>
                    <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Away team</th>
                    <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Date</th>
                    <th class="px-3 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Venue</th>
                    </tr>
                </thead>
                {% for fixture in upcoming_matches %}
                <tbody>
                    <tr>
                    <td class="px-3 py-3">
                        <a href="{% url 'matches:match-detail' fixture.slug %}">
                            {{ fixture.home_team }}
                        </a>
                    </td>
                    <td class="px-3 py-3">
                        <a href="{% url 'matches:match-detail' fixture.slug %}">
                            {{ fixture.away_team }}
                        </a>
                    </td>
                    <td class="px-3 py-3 text-lg text-gray-900">{{ fixture.match_date|date:"F d, Y, h:i A" }}</td>
                    <td class="px-3 py-3">{{ fixture.venue }}
                    </td>
                    </tr>
                </tbody>
                {% endfor %}

                {% for fixture in custom_matches %}
                <tbody>
                    <tr>
                    {% if fixture.is_home %}
                        <td class="px-3 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' fixture.slug %}">
                                {{ fixture.user_team }}
                            </a>
                        </td>
                        <td class="px-3 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' fixture.slug %}">
                                {{ fixture.versus_team }}
                            </a>
                        </td>
                    {% else %}
                        <td class="px-3 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' fixture.slug %}">
                                {{ fixture.versus_team }}
                            </a>
                        </td>
                        <td class="px-3 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' fixture.slug %}">
                                {{ fixture.user_team }}
                            </a>
                        </td>
                    {% endif %}
                    <td class="px-3 py-3 text-lg text-gray-900">{{ fixture.match_date|date:"F d, Y, h:i A" }}</td>
                    <td class="px-3 py-3">{{ fixture.venue }}
                    </td>
                    </tr>
                </tbody>
                {% endfor %}
                </table>
            </div>
        {% else %}
            <h1 class="sm:text-1xl font-medium text-center title-font mt-5">None at this time</h1>
        {% endif %}


        <h1 class="sm:text-4xl text-3xl font-medium title-font mt-5 text-gray-900">Results</h1>
        {% if team_results or custom_results %}
            <div class="lg:w-3/3 w-full mx-auto overflow-auto mb-10">
                <div class="flex flex-col w-full mb-5">
                </div>
                <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Home team</th>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Away team</th>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Scoreline</th>
                    <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Date</th>
                    <th class="w-10 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tr rounded-br"></th>
                    </tr>
                </thead>
                {% for result in team_results %}
                <tbody>
                    <tr>
                    <td class="px-4 py-3">
                        <a href="{% url 'matches:match-detail' result.match.slug %}">
                            {{ result.match.home_team }}
                        </a>
                    </td>
                    <td class="px-4 py-3">
                        <a href="{% url 'matches:match-detail' result.match.slug %}">
                            {{ result.match.away_team }}
                        </a>
                    </td>
                    <td class="px-4 py-3">
                        {% if result.score_hometeam == result.score_awayteam %}
                                <span class="px-2 py-1 mx-2 font-semibold leading-tight text-white bg-gray-500"> D </span>
                            {% elif result.match.home_team == selected_team and result.score_hometeam > result.score_awayteam %}
                                <span class="px-2 py-1 mx-2 font-semibold leading-tight text-white bg-green-500"> W </span>
                            {% elif result.match.away_team == selected_team and result.score_awayteam > result.score_hometeam %}
                                <span class="px-2 py-1 mx-2 font-semibold leading-tight text-white bg-green-500"> W </span>
                            {% else %}
                                <span class="px-2 py-1 mx-2 font-semibold leading-tight text-white bg-red-500"> L </span>
                            {% endif %}
                        {{ result.score_hometeam }} : {{ result.score_awayteam }}</td>
                    <td class="px-4 py-3 text-lg text-gray-900">{{ result.match.match_date|date:"F d, Y, h:i A" }}</td>
                    <td class="px-4 py-3 text-lg text-gray-900">
                    <a class="px-4 py-3 text-lg underline text-blue-900" href="{% url 'matches:match-detail' result.match.slug %}">View</a>
                    </td>
                    </tr>
                </tbody>
                {% endfor %}

                {% for result in custom_results %}
                <tbody>
                    <tr>
                    {% if result.custom_match.is_home %}
                        <td class="px-4 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' result.custom_match.slug %}">
                                {{ result.custom_match.user_team }}
                            </a>
                        </td>
                        <td class="px-4 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' result.custom_match.slug %}">
                                {{ result.custom_match.versus_team }}
                            </a>
                        </td>
                    {% else %}
                        <td class="px-4 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' result.custom_match.slug %}">
                                {{ result.custom_match.versus_team }}
                            </a>
                        </td>
                        <td class="px-4 py-3">
                            <a href="{% url 'custommatches:custommatch-detail' result.custom_match.slug %}">
                                {{ result.custom_match.user_team }}
                            </a>
                        </td>
                    {% endif %}
                    <td class="px-4 py-3">
                        {% if result.score_userteam == result.score_versusteam %}
                            <span class="px-2 py-1 mx-2 font-semibold leading-tight text-white bg-gray-500"> D </span>
                        {% elif result.score_userteam > result.score_versusteam %}
                            <span class="px-2 py-1 mx-2 font-semibold leading-tight text-white bg-green-500"> W </span>
                        {% else %}
                            <span class="px-2 py-1 mx-2 font-semibold leading-tight text-white bg-red-500"> L </span>
                        {% endif %}
                        
                        {% if result.custom_match.is_home %}
                            {{ result.score_userteam }} : {{ result.score_versusteam }}
                        {% else %}
                            {{ result.score_userteam }} : {{ result.score_versusteam }}
                        {% endif %}
                    </td>
                    <td class="px-4 py-3 text-lg text-gray-900">{{ result.custom_match.match_date|date:"F d, Y, h:i A" }}</td>
                    <td class="px-4 py-3 text-lg text-gray-900">
                    <a class="px-4 py-3 text-lg underline text-blue-900" href="{% url 'custommatches:custommatch-detail' result.custom_match.slug %}">View</a>
                    </td>
                    </tr>
                </tbody>
                {% endfor %}
                </table>
            </div>
        {% else %}
            <div class="mb-10">
                <h1 class="sm:text-1xl font-medium text-center title-font mt-5">None at this time</h1>
            </div>
        {% endif %}
    </div>
  </section>

{% endblock content %}