bifefootball/urls.py
from django.contrib import admin
from django.urls import path, include

from players.views import LandingPageView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name="landing-page"),
    path("matches/", include("matches.urls", namespace="matches")),
    path("admins/", include("admins.urls", namespace="admins")),
    path("players/", include("players.urls", namespace="players")),
    path("organizations/", include("organizations.urls", namespace="organizations")),
    path("teams/", include("teams.urls", namespace="teams")),
    path('accounts/', include('allauth.urls')),
    path("custommatches/", include("custommatches.urls", namespace="custommatches")),
]

matches/urls.py
from django.urls import path
from .views import (
    MatchListView,
    MatchDetailView,
    MatchCreateView,
    MatchCreateEventView,
    ResultCreateView,
    PlayerStatCreateEventView,
    UpdateTeamsView,
    )

"""
BASE ENDPOINT /matches
"""
app_name = "matches"

urlpatterns = [
    path("", MatchListView.as_view(), name='match-list'),
    path("create/", MatchCreateView.as_view(), name='match-create'),
    path("create-event/<slug:slug>/", MatchCreateEventView.as_view(), name='match-event-create'),
    path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path('update-teams/', UpdateTeamsView.as_view(), name='update-teams'),
    path("create-playerstat/<slug:slug>/", PlayerStatCreateEventView.as_view(), name='player-stat-create'),
    path("<slug:slug>/", MatchDetailView.as_view(), name='match-detail'),
]

players/urls.py
from django.urls import path
from .views import (
    PlayerListView,
    PlayerDetailView,
    PlayerCreateView,
    PlayerUpdateView,
    PlayerDeleteView,
    PlayerMatchesListView,
    PlayerUpdateTeamsView,
    TeamSelectView,
    )

"""
BASE ENDPOINT /players
"""
app_name = "players"

urlpatterns = [
    path("", PlayerListView.as_view(), name='player-list'),
    path("create/", PlayerCreateView.as_view(), name='player-create'),
    path('select-team/', TeamSelectView.as_view(), name='team-select'),
    path("<slug:slug>/", PlayerDetailView.as_view(), name='player-detail'),
    path("<slug:slug>/update", PlayerUpdateView.as_view(), name='player-update'),
    path('<slug:slug>/update-teams/', PlayerUpdateTeamsView.as_view(), name='player-update-teams'),
    path("<slug:slug>/delete", PlayerDeleteView.as_view(), name='player-delete'),
    path("<slug:slug>/matches", PlayerMatchesListView.as_view(), name='player-matches'),
]

teams/urls.py
from django.urls import path
from .views import (
    TeamListView,
    TeamCreateView,
    TeamDetailView,
    TeamDashboardView,
    TeamMatchesView,
    CoachCreateView,
    TeamSelectView
    )

"""
BASE ENDPOINT /teams
"""
app_name = "teams"

urlpatterns = [
    path("", TeamListView.as_view(), name='team-list'),
    path("create/", TeamCreateView.as_view(), name='team-create'),
    path("create-coach/", CoachCreateView.as_view(), name='coach-create'),
    path('select-team/', TeamSelectView.as_view(), name='team-select'),
    path("team-dashboard/", TeamDashboardView.as_view(), name='team-dashboard'),
    # path("confirm-result/<slug:slug>/", ResultCreateView.as_view(), name='result-create'),
    path("<slug:slug>/team-matches", TeamMatchesView.as_view(), name='team-matches'),
    path("<slug:slug>/", TeamDetailView.as_view(), name='team-detail'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>SoccerBase</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="" />
    {% include 'css.html' %}
    {% comment %} <script src="https://cdn.tailwindcss.com"></script> {% endcomment %}
  </head>

  <body class="bg-gray-300 antialiased">
    {% include "navbar.html" %}
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    {% include 'js.html' %}
    <div class="max-w-7xl mx-auto">
      {% block content %} {% endblock content %}
    </div>
    
    <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
  </body>
</html>

templates/css.html
{% load static %}

{% comment %} <link rel="stylesheet" href="{% static 'vendors/tailwind-out.css' %}" /> {% endcomment %}
<link rel="stylesheet" href="{% static 'vendors/tailwind-out.css' %}" />
<link rel="stylesheet" href="{% static 'vendors/flowbite.min.css' %}" />

<style>
    /* CSS for styling the message box */
    .messages {
        display: flex;
        justify-content: center;
        align-items: center;
        list-style: none;
        padding: 0;
        margin: 20px 0;
    }
    .messages li {
        background-color: #007bff;
        color: white;
        padding: 10px 20px;
        border-radius: 10px;
        margin: 5px 0;
        text-align: center;
        width: fit-content;
    }
</style>

templates/js.html
{% load static %}

{% comment %} <script src="{% static 'js/main.js' %}"></script> {% endcomment %}
<script src="{% static 'vendors/flowbite.min.js' %}"></script>
<script src="{% static 'vendors/htmx.min.js' %}"></script>

templates/landing_page.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
    <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="{% static 'images/football-theme.jpg' %}">
    <div class="text-center lg:w-2/3 w-full">
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Welcome to SoccerBase</h1>
      <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">The Football Team Management App</h1>
      <p class="mb-8 text-xl leading-relaxed">Effortlessly manage your football sports teams, players, and matches. Create teams, add players and coaches, schedule matches, record events, update stats, view past results, and search through our comprehensive database.</p>
      <div class="flex justify-center">
        <a href="{% url 'account_signup' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Create a Team</a>
        <a href="{% url 'matches:match-list' %}" class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">View Matches</a>
      </div>
    </div>
  </div>
</section>

<section class="text-gray-600 body-font">
  <div class="container px-5 py-10 mx-auto">
    <div class="flex flex-col text-center w-full mb-5">
      <h2 class="sm:text-3xl text-3xl font-medium title-font mb-4 text-gray-900">FEATURES</h2>
      <p class="lg:w-2/3 mx-auto leading-relaxed text-xl text-base">Discover the key features of the SoccerBase App designed to help you manage your teams effectively.</p>
    </div>
    <div class="flex flex-wrap justify-center items-center -m-4">
      <div class="p-4 lg:w-1/3 md:w-1/2">
        <div class="h-full bg-gray-100 p-8 rounded">
          <h3 class="text-lg font-medium text-gray-900">Team Management</h3>
          <p class="leading-relaxed text-base mb-4">Create and manage teams, add players and coaches, and update team information seamlessly.</p>
        </div>
      </div>
      <div class="p-4 lg:w-1/3 md:w-1/2">
        <div class="h-full bg-gray-100 p-8 rounded">
          <h3 class="text-lg font-medium text-gray-900">Match Management</h3>
          <p class="leading-relaxed text-base mb-4">Schedule matches, record match events, and keep track of match details easily.</p>
        </div>
      </div>
      <div class="p-4 lg:w-1/3 md:w-1/2">
        <div class="h-full bg-gray-100 p-8 rounded">
          <h3 class="text-lg font-medium text-gray-900">Player Statistics</h3>
          <p class="leading-relaxed text-base mb-4">Track player performance, update stats after each match, and analyze player data effectively.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="text-gray-600 body-font">
  <div class="container mx-auto flex px-5 mt-10 mb-10 items-center justify-center flex-col">
    <div class="text-center lg:w-2/3 w-full">
      <h2 class="title-font sm:text-4xl text-4xl mb-4 font-medium text-gray-900">Get Started Today</h2>
      <p class="mb-8 text-xl leading-relaxed">Join us today and take your team management to the next level with our comprehensive and easy-to-use app. Whether you're managing a local sports team or a professional club, our app has all the tools you need.</p>
      <div class="flex justify-center">
        <a href="{% url 'account_signup' %}" class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Sign Up</a>
        <a href="{% url 'account_login' %}" class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Log In</a>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

templates/navbar.html
<nav class="bg-white border-gray-200 dark:bg-gray-900">
  <div class="container flex flex-wrap items-center md:flex-row justify-between mx-auto p-4">
  <a href="{% url 'landing-page'%}" class="flex items-center space-x-3 rtl:space-x-reverse">
      <span class="self-center text-blue text-2xl font-semibold whitespace-nowrap">SoccerBase</span>
  </a>
  <div class="flex md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">
    {% if not request.user.is_authenticated %}
      <a href="{% url 'account_login' %}">
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Get started</button>
      </a>

      <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
        </svg>
      </button>
    {% else %}
        <button type="button" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Logged in as: {{ request.user.username }}</button>
        <button data-collapse-toggle="navbar-cta" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600" aria-controls="navbar-cta" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 17 14">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 1h15M1 7h15M1 13h15"/>
          </svg>
        </button>
    {% endif %}
  </div>
  <div class="hidden w-full md:flex md:w-auto md:order-1" id="navbar-cta">
    <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
      <li>
        <a href="{% url 'players:player-list' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Players</a>
      </li>
      <li>
        <a href="{% url 'matches:match-list' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Matches</a>
      </li>
      <li>
        <a href="{% url 'teams:team-list' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Teams</a>
      </li>
      {% if request.user.is_coach %}
      <li>
        <a href="{% url 'teams:team-dashboard' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Teams Dashboard</a>
      </li>
      <li>
        <a href="{% url 'matches:match-create' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Schedule Match</a>
      </li>
      <li>
        <a href="{% url 'teams:team-matches' request.user.coach.team.slug %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">My Games</a>
      </li>
      {% endif %}
      {% if request.user.is_authenticated %}
      </li>
      <a href="{% url 'account_logout' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Logout</a>
      </li>
      {% else %}
      <a href="{% url 'account_login' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Login</a>
      <a href="{% url 'account_signup' %}" class="block py-2 px-3 md:p-0 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:dark:hover:text-blue-500 dark:text-white dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Signup</a>
      {% endif %}
    </ul>
  </div>
  </div>
</nav>